### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by vr8hub** [btaylor8/james-branch-cabell_the-cords-of-vanity#1]
- [x] The CSS for the first set of header selectors can have both margin-top and margin-bottom, and then the second set of selectors isn't needed.
- [x] The Story of the Flower Kingdom in chapter 10 is just the poem, so that we need either the section or the blockquote, but not both. I don't think the blockquote is applicable, since he's not quoting someone else, so the poem semantic should therefore go on the section and eliminate the blockquote. Just the blockquote—the rest of the formatting, with the p and spans, stays the same.
- [x] You appear to be on an older version of the tools. Go ahead and update them, and then re-run lint; you will need to update the ignore codes to match the new ones. (The t-042 code was split into various y-XXX codes a while ago.)
- [x] Typogrify makes a change that should be accepted.
- [x] CSS is needed for the Latin blockquote; see [SEMoS 8.2.9.6](https://standardebooks.org/manual/1.7.4/single-page#8.2.9.6).
- [x] Likewise, CSS is needed so the "Jurgen" is not italicized in the introduction quote. (You've surrounded it with `<b>`, but it's not small-capped in the scans.)
- [x] Commit e987609 is changing the text, so should be an Editorial commit.
- [x] On the other hand, commit e122e05 is _not_ changing the text, just as your other "fixing transcription" commits, so should not be editorial.
- [x] And, since we're changing commit messages, 0b48475 has the "git commit -am" in with the message.
- [x] The song in the prologue is missing the beginning quotes for each stanza (and the quotes should match the scans).
- [x] Also, the last line of that song is not italicized as it is in the scans.
- [x] Some of the verse with "poem" semantics are partial quotes, e.g. the ones in ch. 11, ch. 16, ch. 28, and so should be "verse"; see SEMoS 7.5.6.1 (https://standardebooks.org/manual/1.7.4/single-page#7.5.6.1). 
- [x] I think the missing punctuation in the letter in the prologue is intentional, just as the misspelled Amen (and missing comma before it), so they should probably be removed. (It will require ignore entries, I'm sure.)
- [x] The "Fable of the Foolish Prince" in the prologue is a story (everything after the title in section -2 is in quotes), and should thus be formatted as the rest of the stories, i.e. as its own section, with the title as header.
- [x] The story sections should have ids consistent with the others, i.e. prologue-2-1, not the name of the story.
- [x] I'm also not sure about the use of z3998:subsection; they would not seem to qualify for the definition (they're not "major subdivisions," since they're only part of a part). But, I don't know what else might qualify, either. (It may be we leave it off entirely). I'll ask Alex on-list.
- [x] The colon in "But now: I recognize…" in ch. 7.7 is not present in the scans.
- [x] As the clause is standalone, I believe the exclamation on "Depardieux, messire!" should be within the italics.
- [x] Several tagged word/phrases are in M-W, so should not be tagged: e.g. fin de siècle, au revoir, ignis fatuus, etc. Other than long quotes, any word/phrase needs to be checked against M-W; see [SEMoS 8.2.9.4](https://standardebooks.org/manual/1.7.4/single-page#8.2.9.4).
- [x] Since it's prefaced with "some of the new _books_," and there _are_ Mr. Dooley books, even if that isn't the exact title, I think we should go with the scans and tag "Mr. Dooley" as a book in ch. 7.4.
- [x] Only book-length poem names are italicized; short poems are quoted; see [SEMoS 8.2.11](https://standardebooks.org/manual/1.7.4/single-page#8.2.11). They can still have the poem semantic (although I can only find mention of “Me und Gott” as a song), but they're quoted.
- [x] The blockquote in chapter 9 is a letter ("…_wrote_ Uncle George"), so should be tagged as such.
- [x] The "For she is to each man…" paragraph in ch. 11 is not indented, so should have the "continued" class. And since it's not starting a paragraph, which means the quote isn't either, the extra quotes aren't needed. (That differentiates it from the earlier verse in the same chapter; there the quote _is_ a separate paragraph, and so needs its own quotes.) An argument could be made, I suppose, that it should be _single_-quoted, but since the scans don't, and we're not in the business of re-editing the book, I think we leave it as is.
- [x] The "allways" in Avis' letter in ch. 28 is intentional (see the second para of the section), so the commit to correct it should be reverted.

**Comment by btaylor8** [comment]
@vr8hub Thanks for the feedback; I've completed most of the tasks but have questions on the two remaining items:
- The CSS for the second set of headers in the subsections was intentional to override the `core.css`. When I add `margin-bottom: 1em;` in `local.css` into the `header{}` selector (and remove the `> header + *{}` selector), the paragraph after the header uses a 3em top margin due to `core.css`. Should I leave it as-is, or is there another way to override the core css?

  `local.css` before:
  ```css
  ...,
  #chapter-19-3-1 header{
	font-style: italic;
	margin-top: 1em;
  }

  ...,
  #chapter-19-3-1 > header + *{
	margin-top: 1em;
  }
  ```
  `local.css` after:
    ```css
  ...,
  #chapter-19-3-1 header{
	font-style: italic;
	margin-top: 1em;
  margin-bottom: 1em;
  }
  ```
  
  `core.css`:
  ```css
  ...,
  section > header + *{
	margin-top: 3em;
  }
  ```
- When I remove the `<blockquote>` from "The story of the Flowery Kingdom," the poem is no longer indented; also the header is no longer centered due to the addtion of the `epub:type="z3998:poem"` semantic. Should I keep the `<blockquote>` or add CSS specifically for this section to indent the poem properly and center the header? ([link to page in scans](https://archive.org/details/cordsofvanitycom0000cabe/page/100/mode/2up))

**Comment by vr8hub** [comment]
Right, I've been burned by that core CSS more than once; I always forget it's there.
I'll admit up front this could go either way, but I think this is a case for class. Let's put a `class="story-header"` (if you have a class name you prefer, that's fine, I'm not married to that, but it needs to be semantic, i.e. describe what it _is_ rather than what it's _doing_) on the story headers (the `<header>`, not the `p`), and then the two CSS' can be just for .story-header.

For the Flowery Kingdom, that's how we do our poetry collections, but obviously they don't have mixed poetry and prose, like we do here. So, we need some CSS to mimic the formatting. The first selector duplicates the margins for a blockquote. The second selector is because the poem p selector is a higher specificity than the generic header selector (the latter assumes the p's inside it will be centered as well), so we have to override it to get a *poem* header p to be centered.

````
#chapter-10-1-1 {
    margin-bottom: 1em;
    margin-left: 2.5em;
}

#chapter-10-1-1 header > p {
	text-align: center;
}
````

I'll make a note of both of these to Alex when I turn it over to him, so he can blame me if he disagrees. :)

**Comment by btaylor8** [comment]
Thanks, I made the updates per your reply.

**Comment by vr8hub** [comment]
One last nit: typogrify makes changes that should be accepted. (Adding the quotes back in the prologue needs some hair-spaces between the quotes.)

**Comment by btaylor8** [comment]
Fixed; I could have sworn I did that before!
